/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintStream;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author momen
 */
class Node{
    public char data;
    public Node one;
    public Node zero;
    Node(){}
    
    Node(char c){
        data = c;
        one = null;
        zero = null;
    }
    
    Node(Node on , Node ze){
        data = 0;
        one = on;
        zero = ze;
    }
}

public class LZW extends javax.swing.JFrame {

    /**
     * Creates new form LZW
     */
    File file;
    Node node;
    public LZW() {
        initComponents();
    }

    LZW(File fi) {
         file = fi;
         node = null;
         initComponents();
    }
    ArrayList < String > co = new ArrayList<>(0);
    void re(Node no , String s){
        if(no.one == null && no.zero == null){
            co.set(no.data, s);
        }
        else{
            if(no.one != null)
                re(no.one , s + '1');
            if(no.zero != null)
                 re(no.zero , s + '0');
        }
    }
    
    String dere(Node no , int i , String s){
        
        if(no.zero == null && no.one == null) return no.data + dere(node , i , s);
        if(i == s.length()) return "";
        System.out.println(i);
        if(s.charAt(i) == '0'){         
            return dere(no.zero , i + 1, s);
        }
        else{
            return dere(no.one , i + 1, s);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("LZW"));

        jButton1.setText("Compress");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("DeCompress");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Scanner cin = null ;
        try {
            cin = new Scanner(file);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(LZW.class.getName()).log(Level.SEVERE, null, ex);
            System.err.println("Error 404 !");
            System.exit(0);
        }
        String s = cin.next();
        ArrayList < Integer > arr = new ArrayList<>(0);
        for(int i = 0 ; i < 128 ; i++){
            arr.add(0);
        }
        for(int i = 0 ; i < s.length(); i++){
            int n = (s.charAt(i));
            arr.set(n, arr.get(n) + 1);
        }
        ArrayList < Integer  > ar = new ArrayList<>(0);
        ArrayList < Node > a = new ArrayList<>(0);
        for(int i = 0; i < 128 ; i++){
            if(arr.get(i) > 0){
                ar.add(arr.get(i));
                Node ne = new Node((char) i);
                a.add(ne);
            }
        }
        if(ar.size() == 1){
            Node x = null;
            Node y = new Node(a.get(0), x);
            a.set(0, y);
        }
        else while(ar.size() > 1) {
            int n = 1000000 , k = 0 , na = 0;
            for(int j = 0; j < ar.size() ; j++){
                if(ar.get(j) < n){
                    n = ar.get(j) ;
                    k = j;
                }
            }
            na = n;
            Node n1 = new Node();
            n1 = a.get(k);
            a.remove(k);    ar.remove(k);
            n = 1000000 ;
            k = 0;
            for(int j = 0; j < ar.size() ; j++){
                if(ar.get(j) < n){
                    n = ar.get(j) ;
                    k = j;
                }
            }
            Node n2 = new Node();
            n2 = a.get(k);
            a.remove(k);    ar.remove(k);
            Node nn = new Node(n1, n2);
            a.add(nn);
            ar.add(na + n);
        }
        for(int i = 0 ; i < 128 ; i++){
            co.add("");
        }
        node = a.get(0);
        re(a.get(0) , "");
        PrintStream cout = null;
        try {
            cout = new PrintStream(file);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(LZW.class.getName()).log(Level.SEVERE, null, ex);
        }
        for(int i = 0 ; i < s.length();i++){
           cout.print(co.get(s.charAt(i)));
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Scanner cin = null ;
        try {
            cin = new Scanner(file);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(LZW.class.getName()).log(Level.SEVERE, null, ex);
            System.err.println("Error 404 !");
            System.exit(0);
        }
        String s = cin.next();
        PrintStream cout = null;
        try {
            cout = new PrintStream(file);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(LZW.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println(node.one == null);
        System.out.println(node.zero == null);
        cout.println(dere(node , 0 , s));
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LZW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LZW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LZW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LZW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LZW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
